In [2]:
import math
import numpy as np

In [3]:
x=np.array([1,0,1])
w = np.array([[0.2,0.4,-0.5],
     [-0.3,0.1,0.2]])

b = np.array([-0.4,0.2])


In [4]:
x.shape

(3,)

In [5]:
def output_layer(x,w,b):
    inp_res=[]
    for i in range(w.shape[0]) :
        inp =0 
        for j in range(x.shape[0]):
            inp+= x[j]*w[i][j]
        inp+=b[i]
        out = 1/(1+math.exp(-inp))
        inp_res.append(out)
    return inp_res

In [6]:
def final_err(target,final_out):
    
    err_final = final_out * (1-final_out) * (target - final_out)

    return err_final

In [7]:
def hidden_err(output_of_layers,err_final,w):
    err=[]
    for i in range(w.shape[1]):
        e=output_of_layers[i]*(1-output_of_layers[i])*err_final*w[0][i]
        err.append(e)
    return err

In [8]:
def upadate_final_paramete(w_res,b_res,err_final_Layer,output_of_layers):
    for i in range(w_res.shape[1]):
        w_res[0][i] = w_res[0][i]+0.9* err_final_Layer*output_of_layers[i]
    
    for i in range(b_res.shape[0]):
        b_res[i] = b_res[i]+0.9*err_final_Layer
    
    return w_res,b_res

In [9]:
def upadate_hidden_paramete(w,b,hidden_err,x):
    for i in range(w.shape[0]):
        for j in range(x.shape[0]):
            w[i][j] = w[i][j]+0.9*hidden_err[i]*x[i]
    for i in range(w.shape[0]):
        b[i] = b[i]+0.9*hidden_err[i]
    return w,b

### 1St Iteration 

### Output Of first Hidden Layer

In [43]:
inp_to_output = output_layer(x,w,b)
inp_to_output

[0.3318122278318339, 0.52497918747894]

### Output of Final Layer

In [44]:
w_res=np.array([[-0.3,-0.2]])
b_res =np.array([0.1])
final_out = output_layer(np.array(inp_to_output),w_res,b_res)

final_out

[0.47388889882398544]

### Final Layer Error

In [45]:
err_final_Layer = final_err(1, final_out[0])
err_final_Layer

0.1311690782143445

### error Of hidden layer

In [46]:
Err_hidden_layer = hidden_err(inp_to_output,err_final_Layer,w_res)
Err_hidden_layer

[-0.008724561965433263, -0.006542085064168994]

### Updation Of Parameter Of Final Layer

In [47]:
w_res,b_res= upadate_final_paramete(w_res,b_res,err_final_Layer,inp_to_output)
w_res
b_res

array([0.21805217])

In [48]:
w_res

array([[-0.26082885, -0.13802507]])

### Hidden Layer Parameter Updated

In [49]:
w,b = upadate_hidden_paramete(w,b,Err_hidden_layer,x)

In [50]:
w

array([[ 0.19214789,  0.39214789, -0.50785211],
       [-0.3       ,  0.1       ,  0.2       ]])

In [51]:
b

array([-0.40785211,  0.19411212])

### 2nd Iteration

In [52]:
inp_to_output = output_layer(x,w,b)
inp_to_output

[0.32661033886282015, 0.5235106804004694]

In [53]:
w_res=np.array([[-0.3,-0.2]])
b_res =np.array([0.1])
final_out = output_layer(np.array(inp_to_output),w_res,b_res)

final_out

[0.47435122388178186]

In [54]:
err_final_Layer = final_err(1, final_out[0])
err_final_Layer

0.13106639087479113

In [55]:
Err_hidden_layer = hidden_err(inp_to_output,err_final_Layer,w_res)
Err_hidden_layer

[-0.008647866322179376, -0.006538830099366762]

In [56]:
w_res,b_res= upadate_final_paramete(w_res,b_res,err_final_Layer,inp_to_output)
w_res
b_res

array([0.21795975])

In [57]:
w_res

array([[-0.26147313, -0.13824681]])

In [58]:
w,b = upadate_hidden_paramete(w,b,Err_hidden_layer,x)

In [59]:
w

array([[ 0.18436481,  0.38436481, -0.51563519],
       [-0.3       ,  0.1       ,  0.2       ]])

In [60]:
b

array([-0.41563519,  0.18822718])

In [10]:
def compute_result(X,w,b,w_res,b_res,epoch=1):
    for i in range(epoch):
        inp_to_output = output_layer(x,w,b)
        final_out = output_layer(np.array(inp_to_output),w_res,b_res)
        err_final_Layer = final_err(1, final_out[0])
        Err_hidden_layer = hidden_err(inp_to_output,err_final_Layer,w_res)
        w_res,b_res= upadate_final_paramete(w_res,b_res,err_final_Layer,inp_to_output)
        w,b = upadate_hidden_paramete(w,b,Err_hidden_layer,x)

        print("Final Output: ",final_out)
    
    # for i in range(w.shape[0]) :
    #     for j in range(x.shape[0]):
    #         print("W{}{}={}".format(i+1,j+1,w[i][j]))

    # print("W46 = {}".format(w_res[0][0]))
    # print("W56 = {}".format(w_res[0][1]))

    # for i in range(b.shape[0]):
    #     print("B{}={}".format(i,b[i]))
    # print("B6={}".format(b_res[0]))

    print("Updated W for 1st hidden layer:\n", w)
    print("Updated b for 1st hidden layer:\n", b)

    print("Updated W for output layer:\n", w_res)
    print("Updated b for output layer:\n", b_res)


    
    

In [11]:
w_res=np.array([[-0.3,-0.2]])
b_res =np.array([0.1])
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.47388889882398544]
Updated W for 1st hidden layer:
 [[ 0.19214789  0.39214789 -0.50785211]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.40785211  0.19411212]
Updated W for output layer:
 [[-0.26082885 -0.13802507]]
Updated b for output layer:
 [0.21805217]


In [12]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.515146658035532]
Updated W for 1st hidden layer:
 [[ 0.1858955  0.3858955 -0.5141045]
 [-0.3        0.1        0.2      ]]
Updated b for 1st hidden layer:
 [-0.4141045   0.19035954]
Updated W for output layer:
 [[-0.22523097 -0.08096665]]
Updated b for output layer:
 [0.32704406]


In [13]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.5528261950190481]
Updated W for 1st hidden layer:
 [[ 0.18099941  0.38099941 -0.51900059]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.41900059  0.18834978]
Updated W for output layer:
 [[-0.19314527 -0.02897518]]
Updated b for output layer:
 [0.42653507]


In [14]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.5865538225859805]
Updated W for 1st hidden layer:
 [[ 0.17721127  0.37721127 -0.52278873]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.42278873  0.18769739]
Updated W for output layer:
 [[-0.16433257  0.01813553]]
Updated b for output layer:
 [0.51677284]


In [15]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.6163707437928547]
Updated W for 1st hidden layer:
 [[ 0.17430733  0.37430733 -0.52569267]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.42569267  0.18806683]
Updated W for output layer:
 [[-0.13846606  0.06074477]]
Updated b for output layer:
 [0.59841377]


In [16]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.6425646228621961]
Updated W for 1st hidden layer:
 [[ 0.17210003  0.37210003 -0.52789997]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.42789997  0.18918668]
Updated W for output layer:
 [[-0.11519608  0.09931276]]
Updated b for output layer:
 [0.67229845]


In [17]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.6655332401981813]
Updated W for 1st hidden layer:
 [[ 0.17043871  0.37043871 -0.52956129]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.42956129  0.19084703]
Updated W for output layer:
 [[-0.09418794  0.13430914]]
Updated b for output layer:
 [0.73930514]


In [18]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.6856971109573735]
Updated W for 1st hidden layer:
 [[ 0.16920517  0.36920517 -0.53079483]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43079483  0.19288981]
Updated W for output layer:
 [[-0.07513974  0.16617465]]
Updated b for output layer:
 [0.80026888]


In [19]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.703452844089538]
Updated W for 1st hidden layer:
 [[ 0.16830771  0.36830771 -0.53169229]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43169229  0.1951978 ]
Updated W for output layer:
 [[-0.05778805  0.19530446]]
Updated b for output layer:
 [0.85594449]


In [20]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.7191531161608903]
Updated W for 1st hidden layer:
 [[ 0.16767547  0.36767547 -0.53232453]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43232453  0.19768477]
Updated W for output layer:
 [[-0.04190717  0.22204395]]
Updated b for output layer:
 [0.90699536]


In [21]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.7331015860390268]
Updated W for 1st hidden layer:
 [[ 0.16725366  0.36725366 -0.53274634]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43274634  0.20028758]
Updated W for output layer:
 [[-0.0273055   0.24669088]]
Updated b for output layer:
 [0.95399544]


In [22]:
compute_result(x,w,b,w_res,b_res,1)

Final Output:  [0.7455551554403165]
Updated W for 1st hidden layer:
 [[ 0.16699975  0.36699975 -0.53300025]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43300025  0.20296004]
Updated W for output layer:
 [[-0.013821    0.26950013]]
Updated b for output layer:
 [0.99743742]


In [23]:
compute_result(x,w,b,w_res,b_res,10)


Final Output:  [0.7567292458152037]
Final Output:  [0.766803853853552]
Final Output:  [0.775929341950887]
Final Output:  [0.7842315506909104]
Final Output:  [0.7918161311022122]
Final Output:  [0.7987721344958204]
Final Output:  [0.8051749512889325]
Final Output:  [0.8110887024320323]
Final Output:  [0.8165681810659675]
Final Output:  [0.8216604293132113]
Updated W for 1st hidden layer:
 [[ 0.16890858  0.36890858 -0.53109142]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.43109142  0.22918652]
Updated W for output layer:
 [[0.08166182 0.43201102]]
Updated b for output layer:
 [1.30499356]


In [24]:
compute_result(x,w,b,w_res,b_res,20)

Final Output:  [0.8264060210438303]
Final Output:  [0.8308401083740282]
Final Output:  [0.8349932783793905]
Final Output:  [0.8388922571684662]
Final Output:  [0.8425604909044867]
Final Output:  [0.8460186273240009]
Final Output:  [0.849284916510432]
Final Output:  [0.8523755458935153]
Final Output:  [0.8553049214553311]
Final Output:  [0.8580859047614025]
Final Output:  [0.8607300135661736]
Final Output:  [0.8632475922596875]
Final Output:  [0.8656479572430075]
Final Output:  [0.8679395213788121]
Final Output:  [0.8701299009098866]
Final Output:  [0.8722260076324069]
Final Output:  [0.8742341286221433]
Final Output:  [0.8761599954158702]
Final Output:  [0.878008844228493]
Final Output:  [0.8797854685238403]
Updated W for 1st hidden layer:
 [[ 0.17771404  0.37771404 -0.52228596]
 [-0.3         0.1         0.2       ]]
Updated b for 1st hidden layer:
 [-0.42228596  0.26963905]
Updated W for output layer:
 [[0.18128197 0.60241384]]
Updated b for output layer:
 [1.62246784]


In [25]:
compute_result(x,w,b,w_res,b_res,30)

Final Output:  [0.8814942650420429]
Final Output:  [0.8831392742096614]
Final Output:  [0.8847242157129217]
Final Output:  [0.8862525198937132]
Final Output:  [0.8877273555277471]
Final Output:  [0.8891516544607058]
Final Output:  [0.890528133508353]
Final Output:  [0.8918593139679661]
Final Output:  [0.8931475390391408]
Final Output:  [0.894394989410409]
Final Output:  [0.895603697232894]
Final Output:  [0.8967755586723236]
Final Output:  [0.8979123452052923]
Final Output:  [0.8990157138039396]
Final Output:  [0.9000872161346457]
Final Output:  [0.9011283068803968]
Final Output:  [0.9021403512827848]
Final Output:  [0.9031246319877821]
Final Output:  [0.9040823552692374]
Final Output:  [0.9050146566951991]
Final Output:  [0.9059226062945057]
Final Output:  [0.9068072132744149]
Final Output:  [0.9076694303342345]
Final Output:  [0.908510157614839]
Final Output:  [0.9093302463195225]
Final Output:  [0.9101305020377405]
Final Output:  [0.9109116877998813]
Final Output:  [0.91167452688819

In [27]:
compute_result(x,w,b,w_res,b_res,100)

Final Output:  [0.9366770721382258]
Final Output:  [0.9369754390277526]
Final Output:  [0.937269923812378]
Final Output:  [0.9375606080969122]
Final Output:  [0.93784757113425]
Final Output:  [0.9381308899110812]
Final Output:  [0.9384106392298389]
Final Output:  [0.9386868917870783]
Final Output:  [0.9389597182484638]
Final Output:  [0.9392291873205396]
Final Output:  [0.9394953658194457]
Final Output:  [0.939758318736724]
Final Output:  [0.9400181093023678]
Final Output:  [0.9402747990452422]
Final Output:  [0.940528447851006]
Final Output:  [0.9407791140176566]
Final Output:  [0.9410268543088107]
Final Output:  [0.9412717240048283]
Final Output:  [0.941513776951882]
Final Output:  [0.9417530656090694]
Final Output:  [0.9419896410936576]
Final Output:  [0.9422235532245486]
Final Output:  [0.9424548505640455]
Final Output:  [0.9426835804579964]
Final Output:  [0.9429097890743938]
Final Output:  [0.9431335214404929]
Final Output:  [0.943354821478521]
Final Output:  [0.9435737320400363]

In [28]:
compute_result(x,w,b,w_res,b_res,100)

Final Output:  [0.9550710717726656]
Final Output:  [0.9551856318335773]
Final Output:  [0.9552993748044664]
Final Output:  [0.9554123101810732]
Final Output:  [0.9555244473068015]
Final Output:  [0.9556357953758268]
Final Output:  [0.9557463634361278]
Final Output:  [0.9558561603924449]
Final Output:  [0.9559651950091631]
Final Output:  [0.9560734759131274]
Final Output:  [0.9561810115963891]
Final Output:  [0.9562878104188847]
Final Output:  [0.956393880611051]
Final Output:  [0.9564992302763778]
Final Output:  [0.956603867393899]
Final Output:  [0.9567077998206249]
Final Output:  [0.9568110352939168]
Final Output:  [0.9569135814338046]
Final Output:  [0.9570154457452529]
Final Output:  [0.9571166356203703]
Final Output:  [0.9572171583405703]
Final Output:  [0.9573170210786793]
Final Output:  [0.9574162309010003]
Final Output:  [0.9575147947693231]
Final Output:  [0.9576127195428941]
Final Output:  [0.9577100119803378]
Final Output:  [0.9578066787415354]
Final Output:  [0.957902726389